CFLAGS+= -Wall -g -lm

all: ex1 ex2


ex1: ex1.c
	${CC} ${CFLAGS} -o ex1 ex1.c

ex3: ex2.c
	${CC} ${CFLAGS} -o ex2 ex2.c

ex4: ex4.c
	${CC} ${CFLAGS} -o ex4 ex4.c

clean:

	rm -f *.o
	rm -f ex1
	rm -f ex2
	rm -f ex4





