#!/usr/bin/env python3

""" pyskel - Make a Python skeleton file.

"""

import os
import sys


def usage() :
    
    print("""Create an empty Python file.
Usage:
my.py <filename.py>""")
    exit(2)

def main() :
    print('im here')
    exit(2)
if len(sys.argv) <2 : usage()

filename =sys.argv[1]

content = """#!/usr/bin/env python3

import os
import sys
import doctest

\"\"\" {0} Copyright 2011 Wayne Doucette.

\"\"\"


def init() :

    \"\"\" 

    >>> init()
    Hello, World.

    \"\"\"
    

    print("Hello, World.")


doctest.testmod()

""".format(filename)



if os.path.isfile("./%s" %filename) :
   
    print("\nThe file exists, beotch!\n...")
    os.system("head -n4 %s" %filename)
    print("...")
    
    if not input("\n...proceed to overwite file? ") in ("y", "yes", "yep") :
    
        print("Mission aborted.")
        exit(2)

f = open("./%s" %filename, "w")
f.write(content)
f.close()


os.system("chmod +x %s" %filename)
os.system("./%s -v | less" %filename) 
os.system("vi ./%s" %filename)


